env:
  global:
    - NDK_VERSION=r11c

sudo: false

language:
  - android
jdk:
  - oraclejdk8

before_install:
  - echo y|android update sdk --all --no-ui --force --filter tools
  - echo y|android update sdk --all --no-ui --force --filter platform-tools
  - echo y|android update sdk --all --no-ui --force --filter build-tools-23.0.3
  - echo y|android update sdk --all --no-ui --force --filter android-23
  - echo y|android update sdk --all --no-ui --force --filter extra-android-m2repository
  - wget http://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux-x86_64.zip
  - unzip android-ndk-$NDK_VERSION-linux-x86_64.zip |grep -v inflating
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
  - export PATH=${PATH}:${ANDROID_NDK_HOME}

script:
  - ./gradlew build jacocoTestReport --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
